name: GitHub Actions Preview Deployment
env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  REPOSITORY_TYPE: ${{ secrets.REPOSITORY_TYPE }}
  MONGO_BASE_URL: ${{ secrets.MONGO_BASE_URL }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
  PG_HOST: ${{ secrets.PG_HOST }}
  PG_PORT: ${{ secrets.PG_PORT }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB_NAME: ${{ secrets.PG_DB_NAME }}
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  Tests:
    name: Tests
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Get Var NODE_ENV
        run: echo "NODE_ENV is ${{ vars.NODE_ENV }}"

      - name: Get Secret REPOSITORY_TYPE
        run: echo "REPOSITORY_TYPE is ${{ secrets.REPOSITORY_TYPE }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn

      - name: Test
        run: npm run test:integration